//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFoxFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_studentregisteration
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Fathername { get; set; }
        public string Mothername { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Bod { get; set; }
        public string Email { get; set; }
        public string courses { get; set; }
        public Nullable<double> Fees { get; set; }
        public string Duration { get; set; }
        public string File { get; set; }
        public Nullable<System.DateTime> Registrationdate { get; set; }
        public Nullable<int> courseID { get; set; }
        public string uniqueID { get; set; }
        public string Serialno { get; set; }
    }
}
