//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFoxFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Course
    {
        public int ID { get; set; }
        public string Courses { get; set; }
        public Nullable<double> Fees { get; set; }
        public string Duration { get; set; }
        public string File { get; set; }
        public string Desc { get; set; }
    }
}
